version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    depends_on:
      - mongodb
      - postgres
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
